name: Ruby

on: [push, pull_request]

jobs:
  build:
    name: Testing on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run the default task
        run: |
          gem install bundler -v 2.2.4
          bundle install
          bundle exec rake
